# Book settings
title: Build a Quantum Stack
author: Yunong Shi
copyright: "2025"
logo: figures/navibar.png  # Optional: add a logo

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: auto
  timeout: 120
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/godott/quantum-book
  path_to_book: ""
  branch: main

# HTML-specific settings
html:
  favicon: "figures/favicon.svg"
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_download_button: true
  # Fix for relative paths in GitHub Pages
  baseurl: "/quantum-book/"
  navbar_number_sections: false
  home_page_in_navbar: false
  # Use Sphinx Awesome theme
  theme: sphinxawesome_theme
  
# Launch button settings
launch_buttons:
  notebook_interface: classic
  binderhub_url: ""
  colab_url: ""

# Sphinx settings
sphinx:
  config:
    # Fix image paths for GitHub Pages
    html_sourcelink_suffix: ""
    nb_execution_mode: "auto"
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
    
  extra_extensions:
    - sphinx.ext.intersphinx
    
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist